name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: '17'
  #         distribution: 'adopt'
  #     - name: Cache Maven packages
  #       uses: actions/cache@v2
  #       with:
  #         path: ~/.m2
  #         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
  #         restore-keys: ${{ runner.os }}-maven
  #     - name: Build with Maven
  #       run: mvn -B package --file pom.xml
  #     - name: Test with Maven
  #       run: mvn -B test --file pom.xml
  #     - name: Upload test results
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: test-results
  #         path: target/surefire-reports

  # package:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: '17'
  #         distribution: 'adopt'
  #     - name: Cache Maven packages
  #       uses: actions/cache@v2
  #       with:
  #         path: ~/.m2
  #         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
  #         restore-keys: ${{ runner.os }}-maven
  #     - name: Build with Maven
  #       run: mvn -B package --file pom.xml
  #     - name: Upload artefact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: artefact
  #         path: target/*.jar

  notification:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.FROM_EMAIL }}
          password: ${{ secrets.FROM_PASSWORD }}
          subject: Pipeline executado!
          body: Pipeline executado!
          from: ${{ secrets.FROM_EMAIL }}
          to: ${{ secrets.TO_EMAIL }}
          content_type: text/plain


