name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  notification:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.FROM_EMAIL }}
          password: ${{ secrets.FROM_PASSWORD }}
          subject: Pipeline executado!
          body: Pipeline executado!
          from: ${{ secrets.FROM_EMAIL }}
          to: ${{ secrets.TO_EMAIL }}
          content_type: text/plain


